---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit the README.Rmd file -->

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Lab report #1

Follow the instructions posted at <https://ds202-at-isu.github.io/labs.html> for the lab assignment. The work is meant to be finished during the lab time, but you have time until Monday evening to polish things.

Include your answers in this document (Rmd file). Make sure that it knits properly (into the md file). Upload both the Rmd and the md file to your repository.

All submissions to the github repo will be automatically uploaded for grading once the due date is passed. Submit a link to your repository on Canvas (only one submission per team) to signal to the instructors that you are done with your submission.

Step 12.3:

-   Jyotika's Note: I created a DS2020 directory and created a Labs sub directory, I followed the instructions and cloned the github repository via HTTPS. From there I was able to open the lab 1 project on my RStudio

-   Naveen's Note: I joined the DS2020 directory after my teammate created it. I then cloned the repository to my my local files (git clone https..). After cloning, I opened the Project in Rstudio to do the rest of my tasks.

Step 12.4:

-   Jyotika's Note: This is a line from RStudio.

-   Naveen's Note: This is a line from RStudio (The line the textbook asked to commit and save)

Step 12.5:

-   Jyotika's Note: Having problems with pushing to git as I am denied access to the github repo. I was in the wrong repo, I was not in our team2 repo.

-   Naveen's Note: the message was pushed to the GitHub Repo. I helped my classmate debug her issue with the error.

Step 12.6:

-   Jyotika's note: I am able to view it in the browser.

-   Naveen's Note: I can see it in the browser and the knitting worked
